stages:
  - debug
  - triggers

# The pipeline covers a series of triggers to ensure full testing and coverage

# Debug Stage
debug_merge_request:
  stage: debug
  script:
    - echo "Pipeline Source $CI_PIPELINE_SOURCE"
    - echo "Commit Branch (Source) $CI_COMMIT_REF_NAME"
    - echo "Target Branch (Merge Request) $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"

# Conditional Triggers

conditional_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-setup-pre-dev.yml
  rules:
    # Condition 1: Branch is not main, qa, or development
    - if: $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_REF_NAME != "qa" && $CI_COMMIT_REF_NAME != "development"
      when: always
    # Condition 2: Triggered by a push event
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    # Fallback: Skip if no condition matches
    - when: never



#conditional_qa:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-qa.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_COMMIT_BRANCH == "qa"

#conditional_preprod:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-preprod.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod" || $CI_COMMIT_BRANCH == "preprod"

#conditional_production:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-production.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production" || $CI_COMMIT_BRANCH == "production"