stages:
  - triggers

# Trigger for non-development branches
conditional_non_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-setup-pre-dev.yml
  rules:
    - if: $CI_COMMIT_REF_NAME != "development" && $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_REF_NAME != "qa"
      when: always  # Ensure fallback behavior for non-development branches

# Trigger for development branch
conditional_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-development.yml
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
      when: on_success  # Trigger only for merge requests targeting development
    - if: $CI_COMMIT_BRANCH == "development"
      when: on_success  # Trigger only for direct commits to development

#conditional_qa:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-qa.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_COMMIT_BRANCH == "qa"

#conditional_preprod:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-preprod.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod" || $CI_COMMIT_BRANCH == "preprod"

#conditional_production:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-production.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production" || $CI_COMMIT_BRANCH == "production"