image: dart:stable

stages:
  - test

coverage_job:
  stage: test
  script:
    - echo "Running in directory:"
    - pwd
    - echo "Listing root directory:"
    - ls -la /
    - echo "Listing build directory:"
    - ls -la /builds/
    - echo "Listing project root:"
    - ls -la /builds/dartapps/apps/aortem-sdks/firebase-dart-admin-auth-sdk
    - echo "Navigating to the firebase-dart-admin-auth-sdk directory:"
    - cd /builds/dartapps/apps/aortem-sdks/firebase-dart-admin-auth-sdk
    - echo "Listing contents of firebase-dart-admin-auth-sdk:"
    - ls -la
    - echo "Checking if the test directory exists:"
    - if [ -d "test" ]; then echo "Test directory exists"; else echo "Test directory does not exist"; fi
    - echo "Running dart pub get:"
    - dart pub get
    - echo "Running dart tests with coverage:"
    - dart test test --coverage="coverage"
    - echo "Listing coverage directory:"
    - ls -la coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
    when: always
  coverage: '/^TOTAL.+?(\d+\%)$/'
