image: dart:stable

stages:
  - test

coverage_job:
  stage: test
  script:
    - dart pub get
    #- dart test --coverage="coverage"
   # - dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
    - dart test firebase-dart-admin-auth-sdk/test --coverage="coverage
  artifacts:
    paths:
      - coverage/
  coverage: '/^TOTAL.+?(\d+\%)$/'

