stages:
  - triggers

# The pipeline covers a series of triggers to ensure full testing and coverage

# Conditional Triggers

conditional_non_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-setup-pre-dev.yml
  rules:
    - if: $CI_COMMIT_REF_NAME != "development" && $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_REF_NAME != "qa"
    - when: always

conditional_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-development.yml
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development" || $CI_COMMIT_BRANCH == "development"
    - when: always  # Ensure this job always runs as a fallback


#conditional_qa:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-qa.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_COMMIT_BRANCH == "qa"

#conditional_preprod:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-preprod.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod" || $CI_COMMIT_BRANCH == "preprod"

#conditional_production:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-production.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production" || $CI_COMMIT_BRANCH == "production"