stages:
  - debug
  - triggers

# The pipeline covers a series of triggers to ensure full testing and coverage

# Conditional Triggers

debug_merge_request:
  stage: debug
  script:
    - echo "Pipeline Source $CI_PIPELINE_SOURCE"
    - echo "Commit Branch (Source) $CI_COMMIT_REF_NAME"
    - echo "Target Branch (Merge Request) $CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    - echo "User $GITLAB_USER_NAME"
    - echo "Commit SHA $CI_COMMIT_SHA"
    - echo "Pipeline ID $CI_PIPELINE_ID"


conditional_non_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-setup-pre-dev.yml
  rules:
    - if: $CI_COMMIT_REF_NAME != "main" && $CI_COMMIT_REF_NAME != "qa" && $CI_COMMIT_REF_NAME != "development"

conditional_development:
  stage: triggers
  trigger:
    include: tools/pipelines/child-ci-setup-pre-dev.yml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
      when: always

     # Run for direct push to 'development' only if user is a maintainer or owner for protected pipeline.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "development"
      when: always
    - when: never  # Ensures this doesn't run if no condition matches

#conditional_qa:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-qa.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_COMMIT_BRANCH == "qa"

#conditional_preprod:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-preprod.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod" || $CI_COMMIT_BRANCH == "preprod"

#conditional_production:
#  stage: triggers
#  trigger:
#    include: tools/pipelines/child-ci-production.yml
#  rules:
#    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "production" || $CI_COMMIT_BRANCH == "production"