name: firebase_dart_admin_auth_sdk
description: Firebase Dart SDK For Authentication.
version: 0.0.1-pre
repository: https://github.com/aortem/firebase-dart-admin-auth-sdk

environment:
  sdk: ^3.4.4

# Add regular dependencies here.

dependencies:
  http: ^1.2.1 # Manages our API Request

dev_dependencies:
  ds_tools_testing: ^0.0.1-pre+2
