name: aortem_firebase_dart_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.1-pre
repository: https://github.com/aortem/firebase-dart-admin-auth-sdk

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
