stages:
  - setup

# Setup Stage
setup:
  stage: setup
  image: dart:stable
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
    - if: $CI_COMMIT_REF_NAME == "development" && $GITLAB_USER_LOGIN == "alphabetacreatives"
      when: always
    - when: never
  script:
    - echo "Setting up environment..."
    - cd firebase-dart-admin-auth-sdk/
    - echo "Current directory contents:"
    - ls

    # Fetch dependencies and handle dependency warnings gracefully
    - dart pub get || echo "Dependency issues detected, continuing pipeline..."
    - dart pub outdated || echo "Outdated dependencies detected. Review above output for details."

    # Run Dart analysis
    - echo "Running Dart analysis..."
    - dart analyze > analysis_report.txt || echo "Analysis completed with warnings/errors. Check analysis_report.txt."

    # Filter output for documentation issues, warnings, and errors, excluding test/unit files
    - echo "Filtering for issues excluding test/unit files..."
    - grep -E "(Missing documentation for a public member|info|warning|error)" analysis_report.txt | grep -vE "^test/unit" > filtered_report.txt || echo "No relevant issues found."

    # Check for responsible developers
    - echo "Checking for responsible developers..."
    - |
      while IFS= read -r line; do
        # Extract file path from the filtered report
        file=$(echo $line | awk -F ':' '{print $1}')
        if [[ -n "$file" ]]; then
          # Get the last commit hash for the file
          git_log=$(git log -n 1 --pretty=format:"%h" -- $file)
          echo "File: $file - Last modified in commit: $git_log"
          echo "Issue found: $line"
        else
          echo "No file information could be extracted from: $line"
        fi
      done < filtered_report.txt

    - echo "Analysis complete. Please address the warnings above if applicable."
  artifacts:
    paths:
      - .dart_tool/
      - analysis_report.txt
      - filtered_report.txt
    expire_in: 1h
  retry: 2
