stages:
  - setup_and_analyze

# Setup and Analyze Main Project
setup_and_analyze_main:
  stage: setup_and_analyze
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - echo "Setting up and analyzing the main project..."
    - cd firebase-dart-admin-auth-sdk
    - echo "Running dart pub get in main project..."
    - dart pub get || echo "Error running dart pub get in main project. Continuing pipeline."
    - echo "Running dart analyze in main project..."
    - dart analyze > analysis_report.txt || echo "Analysis completed with warnings/errors. Check analysis_report.txt."
  artifacts:
    paths:
      - firebase-dart-admin-auth-sdk/analysis_report.txt
      - firebase-dart-admin-auth-sdk/.dart_tool/
    expire_in: 1h

# Setup and Analyze Example Project
setup_and_analyze_example:
  stage: setup_and_analyze
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - echo "Setting up and analyzing the example project..."
    - cd firebase-dart-admin-auth-sdk/example/firebase-dart-admin-auth-sdk-sample-app
    - echo "Running flutter pub get in example project..."
    - flutter pub get || echo "Error running flutter pub get in example project. Continuing pipeline."
    - echo "Running dart analyze in example project..."
    - dart analyze > analysis_report_example.txt || echo "Analysis completed with warnings/errors. Check analysis_report_example.txt."
  dependencies:
    - setup_and_analyze_main
  artifacts:
    paths:
      - firebase-dart-admin-auth-sdk/example/firebase-dart-admin-auth-sdk-sample-app/analysis_report_example.txt
      - firebase-dart-admin-auth-sdk/example/firebase-dart-admin-auth-sdk-sample-app/.dart_tool/
    expire_in: 1h
