name: firebase_dart_admin_auth_sdk
description: A Dart SDK for Firebase Admin Authentication, enabling secure server-side authentication and user management for Dart-based backend applications.
version: 0.0.1-pre+2
repository: https://github.com/aortem/firebase-dart-admin-auth-sdk

environment:
  sdk: ^3.4.4

# Add regular dependencies here.

dependencies:
  ds_standard_features: ^0.0.1-pre+8 #Standard Dart Team Utilities
  

dev_dependencies:
  ds_tools_testing: ^0.0.1-pre+2 #Standard Dart Team Testing Tools

