name: firebase_dart_admin_auth_sdk
description: Firebase Dart SDK For Authentication.
version: 0.0.1-pre
repository: https://github.com/aortem/firebase-dart-admin-auth-sdk

environment:
  sdk: ^3.4.3

# Add regular dependencies here.

dependencies:
  ds_standard_features: ^0.0.1-pre+7 #Standard Dart Team Utilities
  

dev_dependencies:
  ds_tools_testing: ^0.0.1-pre+2 #Standard Dart Team Testing Tools

